# encoding: utf-8
"""
@author: XLYF
@file: Outline.py
@time: 2020/11/24 16:25
@desc:
"""
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Role.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from myWidget import myWidget
import source_rc


class OutlineForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setMinimumSize(QtCore.QSize(120, 450))
        self.scrollArea.setMaximumSize(QtCore.QSize(200, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollArea.setStyleSheet("background: transparent")

        # 目录文件按钮存放容器
        self.scrollAreaWidgetContents = myWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 116, 446))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)

        self.scrollArea_2 = QtWidgets.QScrollArea(Form)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(120, 150))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(200, 150))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollArea_2.setStyleSheet("background: transparent")

        # 工具按钮存放路径
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 116, 146))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        # to main window
        self.MainButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.MainButton.setObjectName("MainButton")
        self.verticalLayout_2.addWidget(self.MainButton)

        # to body window
        self.BodyButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.BodyButton.setObjectName("BodyButton")
        self.verticalLayout_2.addWidget(self.BodyButton)

        # create new file
        self.NewBUtton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.NewBUtton.setObjectName("NewButton")
        self.verticalLayout_2.addWidget(self.NewBUtton)

        # delete file
        self.DeleteButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.DeleteButton.setObjectName("DeleteButton")
        self.verticalLayout_2.addWidget(self.DeleteButton)

        # save content
        self.SaveButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.DeleteButton.setObjectName("SaveButton")
        self.verticalLayout_2.addWidget(self.SaveButton)

        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)

        self.InputArea = QtWidgets.QTextEdit(Form)
        self.InputArea.setMinimumSize(QtCore.QSize(680, 600))
        self.InputArea.setStyleSheet("font: 16pt \"隶书\"")       # 设置文本字体
        self.InputArea.setObjectName("InputArea")
        self.InputArea.setFocusPolicy(QtCore.Qt.NoFocus)         # 无焦点，不可编辑
        self.horizontalLayout.addWidget(self.InputArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Outline"))
        self.MainButton.setText(_translate("Form", "主页"))
        self.BodyButton.setText(_translate("Form", "正文"))
        self.NewBUtton.setText(_translate("Form", "新建"))
        self.DeleteButton.setText(_translate("Form", "删除"))
        self.SaveButton.setText(_translate("Form", "保存"))